#!/bin/bash

# source the ciop functions (e.g. ciop-log, ciop-getparam)
source ${ciop_job_include}

node="snap"

source /application/${node}/lib/functions.sh

trap cleanExit EXIT

while read input
do
  main ${input} || exit $?
done
